### ISSUE TITLE
Chyba po změně hesla (zapomenuté heslo)

### ISSUE THREAD

**Issue by zabak** [moravianlibrary/CDArcha-server#28]
Po obnovení zapomenutého hesla se po přihlášení objeví jen chyba:

Error: data and hash arguments required
    at Object.compare (/home/cdarcha/cdarcha/node_modules/bcrypt/bcrypt.js:208:17)
    at model.comparePassword (/home/cdarcha/cdarcha/models/User.js:47:10)
    at /home/cdarcha/cdarcha/config/passport.js:30:10
    at /home/cdarcha/cdarcha/node_modules/mongoose/lib/model.js:4998:18
    at processTicksAndRejections (node:internal/process/task_queues:78:11)

**Comment by cosmo-cz** [comment]
V řešení.

**Comment by cosmo-cz** [comment]
Vyřešeno.
